//for calculator   constant

export const CREATE_CALCULATOR_REQUEST = 'CREATE_CALCULATOR_REQUEST'
export const CREATE_CALCULATOR_SUCCESS ='CREATE_CALCULATOR_SUCCESS'
export const CREATE_CALCULATOR_FAIL ='CREATE_CALCULATOR_FAIL'


//for shipping rate create
export const CREATE_SHIPPING_RATE_REQUEST = 'CREATE_SHIPPING_RATE_REQUEST'
export const CREATE_SHIPPING_RATE_SUCCESS ='CREATE_SHIPPING_RATE_SUCCESS'
export const CREATE_SHIPPING_RATE_FAIL ='CREATE_SHIPPING_RATE_FAIL'


//for delete shipping rate create
export const DELETE_SHIPPING_RATE_REQUEST = 'DELETE_SHIPPING_RATE_REQUEST'
export const DELETE_SHIPPING_RATE_SUCCESS ='DELETE_SHIPPING_RATE_SUCCESS'
export const DELETE_SHIPPING_RATE_FAIL ='DELETE_SHIPPING_RATE_FAIL'

