//for calculator   constant

export const CREATE_CALCULATOR_REQUEST = 'CREATE_CALCULATOR_REQUEST'
export const CREATE_CALCULATOR_SUCCESS ='CREATE_CALCULATOR_SUCCESS'
export const CREATE_CALCULATOR_FAIL ='CREATE_CALCULATOR_FAIL'