// for get delivery address
export const DELIVERY_ADDRESS_REQUEST = 'DELIVERY_ADDRESS_REQUEST'
export const DELIVERY_ADDRESS_SUCCESS = 'DELIVERY_ADDRESS_SUCCESS'
export const DELIVERY_ADDRESS_FAIL = 'DELIVERY_ADDRESS_FAIL'