
// incoming package constant

export const INCOMING_PACKAGE_REQUEST = 'INCOMING_PACKAGE_REQUEST'
export const INCOMING_PACKAGE_SUCCESS ='INCOMING_PACKAGE_SUCCESS'
export const INCOMING_PACKAGE_FAIL ='INCOMING_PACKAGE_FAIL'



//single package constant

export const INCOMING_PACKAGE_DETAIL_REQUEST = 'INCOMING_PACKAGE_DETAIL_REQUEST'
export const INCOMING_PACKAGE_DETAIL_SUCCESS ='INCOMING_PACKAGE_DETAIL_SUCCESS'
export const INCOMING_PACKAGE_DETAIL_FAIL ='INCOMING_PACKAGE_DETAIL_FAIL'
export const INCOMING_PACKAGE_DETAIL_RESET ='INCOMING_PACKAGE_DETAIL_RESET'


//for update package  for admin
export const PACKAGE_UPDATE_REQUEST = 'PACKAGE_UPDATE_REQUEST'
export const PACKAGE_UPDATE_SUCCESS = 'PACKAGE_UPDATE_SUCCESS'
export const PACKAGE_UPDATE_FAIL = 'PACKAGE_UPDATE_FAIL'
export const PACKAGE_UPDATE_RESET = 'PACKAGE_UPDATE_RESET'