
// incoming package constant

export const INCOMING_PACKAGE_REQUEST = 'INCOMING_PACKAGE_REQUEST'
export const INCOMING_PACKAGE_SUCCESS ='INCOMING_PACKAGE_SUCCESS'
export const INCOMING_PACKAGE_FAIL ='INCOMING_PACKAGE_FAIL'



//single package constant

export const INCOMING_PACKAGE_DETAIL_REQUEST = 'INCOMING_PACKAGE_DETAIL_REQUEST'
export const INCOMING_PACKAGE_DETAIL_SUCCESS ='INCOMING_PACKAGE_DETAIL_SUCCESS'
export const INCOMING_PACKAGE_DETAIL_FAIL ='INCOMING_PACKAGE_DETAIL_FAIL'