
//OUTGOING package constant

export const OUTGOING_PACKAGE_REQUEST = 'OUTGOING_PACKAGE_REQUEST'
export const OUTGOING_PACKAGE_SUCCESS ='OUTGOING_PACKAGE_SUCCESS'
export const OUTGOING_PACKAGE_FAIL ='OUTGOING_PACKAGE_FAIL'



//OUTGOING package constant

export const OUTGOING_PACKAGE_DETAIL_REQUEST = 'OUTGOING_PACKAGE_DETAIL_REQUEST'
export const OUTGOING_PACKAGE_DETAIL_SUCCESS ='OUTGOING_PACKAGE_DETAIL_SUCCESS'
export const OUTGOING_PACKAGE_DETAIL_FAIL ='OUTGOING_PACKAGE_DETAIL_FAIL'