
//for get all OUTGOING package constant

export const OUTGOING_PACKAGE_REQUEST = 'OUTGOING_PACKAGE_REQUEST'
export const OUTGOING_PACKAGE_SUCCESS ='OUTGOING_PACKAGE_SUCCESS'
export const OUTGOING_PACKAGE_FAIL ='OUTGOING_PACKAGE_FAIL'


//for get single OUTGOING package constant

export const OUTGOING_PACKAGE_DETAIL_REQUEST = 'OUTGOING_PACKAGE_DETAIL_REQUEST'
export const OUTGOING_PACKAGE_DETAIL_SUCCESS ='OUTGOING_PACKAGE_DETAIL_SUCCESS'
export const OUTGOING_PACKAGE_DETAIL_FAIL ='OUTGOING_PACKAGE_DETAIL_FAIL'

//for create OutGoing package constant

export const OUTGOING_PACKAGE_CREATE_REQUEST = 'OUTGOING_PACKAGE_CREATE_REQUEST'
export const OUTGOING_PACKAGE_CREATE_SUCCESS ='OUTGOING_PACKAGE_CREATE_SUCCESS'
export const OUTGOING_PACKAGE_CREATE_FAIL ='OUTGOING_PACKAGE_CREATE_FAIL'

//for delete outgoing package

export const OUTGOING_PACKAGE_DELETE_REQUEST = 'OUTGOING_PACKAGE_DELETE_REQUEST'
export const OUTGOING_PACKAGE_DELETE_SUCCESS ='OUTGOING_PACKAGE_DELETE_SUCCESS'
export const OUTGOING_PACKAGE_DELETE_FAIL ='OUTGOING_PACKAGE_DELETE_FAIL'


